# Generated by Django 5.2.7 on 2025-11-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_documents/', verbose_name='Arquivo')),
                ('status', models.CharField(choices=[('UPLOADED', 'Enviado (Processando)'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='UPLOADED', max_length=20, verbose_name='Status')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído (OCR)')),
                ('notes_hr', models.TextField(blank=True, null=True, verbose_name='Feedback do RH (Motivo da Rejeição)')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Tipo de Documento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Documento de Funcionário',
                'verbose_name_plural': 'Documentos de Funcionários',
                'ordering': ['-uploaded_at'],
                'unique_together': {('owner', 'doc_type')},
            },
        ),
    ]
