# Generated by Django 5.2.7 on 2025-11-01 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Enviado (Processando)'), ('REVIEW', 'Aguardando Revisão'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='UPLOADED', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('CONTAINS_TEXT', 'Deve Conter o Texto'), ('CONTAINS_KEY', 'Deve Conter a Chave (ex: "CPF:")'), ('REGEX_MATCH', 'Deve Corresponder ao Padrão (Regex)')], max_length=20, verbose_name='Tipo de Regra')),
                ('rule_value', models.CharField(max_length=255, verbose_name='Valor/Texto/Padrão a verificar')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição (Opcional)')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='documents.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Regra de Validação',
                'verbose_name_plural': 'Regras de Validação',
            },
        ),
    ]
